import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Next JS Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div
          className={`${styles.hero1} p-5 text-center bg-image hero1`}
        >
            <div className='justify-content-center align-items-center'>
              <div className={`${styles.hero1Div}`}>
                <div className='text-warning mb-3'>
                  <b className={`${styles.catchphrase}`}>Unlock your potential</b>
                </div>
                <div className='mb-3'>
                  <b className={`${styles.subheading}`}>Empowering students and educators for a brighter tomorrow.</b>
                </div>
                <a className='btn btn-warning' href='#about' role='button'>
                  Learn More
                </a>
              </div>
            </div>
        </div>
        <div className={`${styles.about}`} id='about'>
          <div className={`${styles.aboutGrid}`}>
          <div className={`${styles.aboutCards} card`}>
              <div className='card-body'>
                <b className='card-title'>Students</b>
                <p className='card-text'>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna. Nunc viverra imperdiet enim. Fusce est. Vivamus a tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci. Aenean nec lorem. In porttitor. Donec laoreet nonummy augue. Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.
                </p>
              </div>
            </div>
            <div className={`${styles.aboutCards} card`}>
              <div className='card-body'>
                <b className='card-title'>Teachers</b>
                <p className='card-text'>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna. Nunc viverra imperdiet enim. Fusce est. Vivamus a tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci. Aenean nec lorem. In porttitor. Donec laoreet nonummy augue. Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.
                </p>
              </div>
            </div>
            <div className={`${styles.aboutCards} card`}>
              <div className='card-body'>
                <b className='card-title'>School District</b>
                <p className='card-text'>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna. Nunc viverra imperdiet enim. Fusce est. Vivamus a tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci. Aenean nec lorem. In porttitor. Donec laoreet nonummy augue. Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.
                </p>
              </div>
            </div>

          </div>
        </div>
      </main>
    </>
  )
}
